---
# Source: ethlogger/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ethlogger
  labels:
    app.kubernetes.io/name: ethlogger
    app.kubernetes.io/instance: ethlogger
    app.kubernetes.io/managed-by: Helm
